/**
 * Explicit turn state machine driving one voice conversation: pumps
 * `ctx.speech` STT turn-detection events, streams the Harness LLM's
 * (`@deepseek-ai/dsh-llm`) response text directly into an open TTS session,
 * and reconciles barge-in against the provider's exact `textSpoken`/
 * `textRemaining` split. Cordis- and session-log-free by design —
 * `./session-log.ts` is the opt-in module that wires this engine's
 * callbacks to a live `Session` and appends the durable `speech-agent/*`
 * events; this class owns only the wire-neutral orchestration, so it is
 * testable against fake `SttSession`/`TtsSession` objects with no Cordis
 * context and no network at all.
 * @module @deepseek-ai/dsh-speech-agent/controller
 */

import { assertNever, type StreamChunk } from '@deepseek-ai/dsh-llm'
import { SpeechError } from '@deepseek-ai/dsh-speech'
import type {
  SttSession,
  SttTurnEvent,
  TtsSession,
  TtsTurnCompletedEvent,
  TtsTurnInterruptedEvent,
  TtsWarningEvent,
} from '@deepseek-ai/dsh-speech'
import { PlaybackClock } from './playback-clock.ts'

/**
 * The conversation's current phase. `idle` never recurs after
 * {@link SpeechAgentController.run} starts (the controller immediately
 * begins `listening`); it exists for a caller that inspects
 * {@link SpeechAgentController.currentState} before `run()`.
 */
export type TurnState = 'idle' | 'listening' | 'thinking' | 'speaking'

/**
 * A TTS turn that finished naturally (no barge-in): the full response was
 * both generated by the LLM and heard by the listener, so `generatedText`
 * and the turn's spoken audio agree completely. Carried by
 * {@link TurnControllerHandlers.onTurnCompleted}.
 */
export interface SpeechAgentTurnCompleted extends TtsTurnCompletedEvent {
  /** The complete assistant text the LLM produced for this response. */
  readonly generatedText: string
}

/**
 * A TTS turn cancelled by barge-in: the exact, durable split between what
 * the LLM generated (`generatedText`) and what the listener actually heard
 * before the interrupt landed (`heardText`, `remainingText`). `heardText`
 * falls back to `generatedText` only when the provider's `turn-interrupted`
 * event carries no `textSpoken` (no playback offset was supplied to
 * `interrupt()`) — every barge-in this controller drives supplies one via
 * {@link PlaybackClock}, so that fallback is defensive, not the normal path.
 * Carried by {@link TurnControllerHandlers.onSpeechInterrupted}.
 */
export interface SpeechAgentTurnInterrupted extends TtsTurnInterruptedEvent {
  /** The complete assistant text the LLM had generated for this response up to the abort. */
  readonly generatedText: string
  /** The portion of `generatedText` the listener actually heard; see the fallback note above. */
  readonly heardText: string
}

/**
 * Callbacks the controller drives as the conversation progresses. Every
 * handler is synchronous and fire-and-forget from the controller's
 * perspective — a consumer that needs to append a session event or update UI
 * state does so inside the callback; a throwing handler propagates out of the
 * controller's internal pump loop and reaches {@link SpeechAgentController.run}'s
 * rejection, ending the conversation.
 */
export interface TurnControllerHandlers {
  /** The turn state changed. Optional — most consumers care only about the terminal events below. */
  onStateChange?(state: TurnState): void
  /**
   * A user utterance's turn detection completed; `turn.transcript` is the
   * final text about to be sent to {@link TurnControllerOptions.respond}.
   */
  onTranscript(turn: SttTurnEvent): void
  /** One text delta the model produced, forwarded to TTS in the same call. Optional — for UI echo only. */
  onAssistantTextDelta?(text: string): void
  /**
   * One binary audio chunk to render. Never called for a chunk the
   * controller determined was stale (see
   * {@link SpeechAgentController.discardedFrameCount}).
   */
  onAudio(chunk: Uint8Array): void
  /**
   * Barge-in was detected: stop rendering any already-buffered audio for
   * the current response immediately, before the provider round trip
   * completes.
   */
  onHaltPlayback(): void
  /** The active TTS turn finished naturally (no barge-in): `generatedText` and the heard audio agree completely. */
  onTurnCompleted?(event: SpeechAgentTurnCompleted): void
  /** The active TTS turn was cancelled by barge-in; carries the exact generated-vs-heard split for durable conversation reconciliation. */
  onSpeechInterrupted(event: SpeechAgentTurnInterrupted): void
  /** A non-fatal provider notice. Optional — synthesis continues without caller action. */
  onWarning?(event: TtsWarningEvent): void
  /** A fatal STT/TTS transport or protocol failure, or an LLM response failure not caused by barge-in cancellation. */
  onError(error: Error): void
}

/** Constructor options for {@link SpeechAgentController}. */
export interface TurnControllerOptions {
  /** The open STT session driving turn detection; the controller consumes its `events` for the whole conversation. */
  readonly stt: SttSession
  /** The open TTS session receiving `speak()`/`flush()`/`interrupt()` calls. */
  readonly tts: TtsSession
  /**
   * Session-wide playback-position clock; a caller driving real audio
   * reports progress through {@link SpeechAgentController.reportPlayed}.
   */
  readonly playbackClock: PlaybackClock
  /**
   * Produce the assistant's streaming response to one final transcript.
   * Reusing `@deepseek-ai/dsh-llm`'s `StreamChunk` vocabulary directly (rather
   * than a narrower text-only contract) keeps this the same stream a real
   * `ctx.llm.stream()` call already produces — see
   * `./llm-responder.ts`'s `createLlmResponder`, which binds exactly this
   * signature to a live `LlmRuntime`. The controller consumes only
   * `text-delta` chunks and treats the stream's end as the response's end.
   * @param transcript - the completed user turn's final text.
   * @param signal - aborted the instant a barge-in cancels this response;
   *   propagate it into the underlying `ctx.llm.stream()` call so the
   *   provider request itself is cancelled, not just its local consumption.
   */
  readonly respond: (transcript: string, signal: AbortSignal) => AsyncIterable<StreamChunk>
  readonly handlers: TurnControllerHandlers
}

/**
 * Drives one voice conversation end to end. Barge-in reconciliation: a fresh
 * STT turn starting while the controller is `thinking` or `speaking` aborts
 * the in-flight LLM response, halts local playback, sends `interrupt()` with
 * the session-wide playback offset, and bumps an internal generation counter
 * so any audio already in flight for the cancelled response is dropped
 * instead of reaching {@link TurnControllerHandlers.onAudio} — see
 * {@link SpeechAgentController.discardedFrameCount}.
 */
export class SpeechAgentController {
  private state: TurnState = 'idle'
  /** Bumped on every barge-in; invalidates the in-flight response and any TTS turn it started. */
  private generation = 0
  /** The generation whose TTS turn is currently producing audio, or `undefined` before the first `turn-started`. */
  private speakingGeneration: number | undefined
  private discardedAudioFrames = 0
  private currentAbort: AbortController | undefined
  private closed = false
  /**
   * Text accumulated per response generation, from `text-delta` chunks
   * forwarded to `tts.speak()`. Read back when the matching TTS turn
   * completes or is interrupted, to record the exact generated-vs-heard
   * split; entries are deleted once reconciled so the map never grows past
   * the number of concurrently unreconciled responses (at most one, absent
   * a provider that reorders `turn-completed`/`turn-interrupted`).
   */
  private readonly generatedTextByGeneration = new Map<number, string>()

  /**
   * @param options - the open sessions, playback clock, responder, and handlers driving this conversation.
   */
  constructor(private readonly options: TurnControllerOptions) {}

  /** The controller's current phase. */
  get currentState(): TurnState {
    return this.state
  }

  /** Audio chunks dropped because they belonged to a response superseded by barge-in before they arrived. */
  get discardedFrameCount(): number {
    return this.discardedAudioFrames
  }

  /**
   * Start pumping both sessions' events for the life of the conversation.
   * @returns settles once both `events` streams end (normal session close) or rejects on an unhandled pump failure.
   */
  async run(): Promise<void> {
    this.setState('listening')
    await Promise.all([this.pumpStt(), this.pumpTts()])
  }

  /**
   * Report locally rendered playback progress, advancing the session-wide
   * {@link PlaybackClock} a caller driving real audio output owns.
   * @param ms - non-negative milliseconds of audio the sink has just rendered.
   */
  reportPlayed(ms: number): void {
    this.options.playbackClock.advance(ms)
  }

  /**
   * Close both underlying sessions and stop pumping. Idempotent.
   * @returns settles once both sessions have closed.
   */
  async close(): Promise<void> {
    if (this.closed) return
    this.closed = true
    this.currentAbort?.abort()
    await Promise.all([this.options.stt.close(), this.options.tts.close()])
  }

  private setState(next: TurnState): void {
    if (this.state === next) return
    this.state = next
    this.options.handlers.onStateChange?.(next)
  }

  private async pumpStt(): Promise<void> {
    try {
      for await (const event of this.options.stt.events) {
        if (event.type !== 'turn') continue
        if (event.kind === 'started' && (this.state === 'thinking' || this.state === 'speaking')) {
          this.bargeIn()
        }
        if (event.kind === 'completed') {
          this.options.handlers.onTranscript(event)
          this.beginResponse(event.transcript)
        }
      }
    } catch (error) {
      this.options.handlers.onError(error instanceof Error ? error : new Error(String(error)))
    }
  }

  private async pumpTts(): Promise<void> {
    try {
      for await (const event of this.options.tts.events) {
        switch (event.type) {
          case 'turn-started':
            this.speakingGeneration = this.generation
            this.setState('speaking')
            break
          case 'audio':
            if (this.speakingGeneration === this.generation) {
              this.options.handlers.onAudio(event.data)
            } else {
              this.discardedAudioFrames += 1
            }
            break
          case 'turn-completed':
            this.options.handlers.onTurnCompleted?.({
              ...event,
              generatedText: this.takeGeneratedText(this.speakingGeneration),
            })
            this.setState('listening')
            break
          case 'turn-interrupted': {
            const generatedText = this.takeGeneratedText(this.speakingGeneration)
            this.options.handlers.onSpeechInterrupted({
              ...event,
              generatedText,
              heardText: event.textSpoken ?? generatedText,
            })
            this.setState('listening')
            break
          }
          case 'warning':
            this.options.handlers.onWarning?.(event)
            break
          case 'error':
            this.options.handlers.onError(new SpeechError(event.message, event.code))
            break
          case 'connected':
          case 'turn-flushed':
          case 'session-completed':
          case 'configure-ack':
          case 'closed':
            break
          default:
            assertNever(event, 'SpeechAgentController.pumpTts')
        }
      }
    } catch (error) {
      this.options.handlers.onError(error instanceof Error ? error : new Error(String(error)))
    }
  }

  /**
   * Read back and clear the accumulated generated text for one TTS turn's
   * originating generation. Absent generation (no response ever produced a
   * delta, e.g. an empty LLM stream) reads back as an empty string rather
   * than throwing — an empty response is a valid, if unusual, outcome.
   */
  private takeGeneratedText(generation: number | undefined): string {
    if (generation === undefined) return ''
    const text = this.generatedTextByGeneration.get(generation) ?? ''
    this.generatedTextByGeneration.delete(generation)
    return text
  }

  private beginResponse(transcript: string): void {
    const myGeneration = ++this.generation
    this.generatedTextByGeneration.set(myGeneration, '')
    this.setState('thinking')
    const controller = new AbortController()
    this.currentAbort = controller
    void this.streamResponse(transcript, myGeneration, controller.signal)
  }

  private async streamResponse(transcript: string, myGeneration: number, signal: AbortSignal): Promise<void> {
    try {
      for await (const chunk of this.options.respond(transcript, signal)) {
        if (myGeneration !== this.generation) return
        if (chunk.type === 'text-delta') {
          const soFar = this.generatedTextByGeneration.get(myGeneration) ?? ''
          this.generatedTextByGeneration.set(myGeneration, soFar + chunk.text)
          this.options.handlers.onAssistantTextDelta?.(chunk.text)
          this.options.tts.speak(chunk.text)
        }
      }
      if (myGeneration === this.generation) this.options.tts.flush()
    } catch (error) {
      // A barge-in's abort() surfaces here as the respond() stream's own
      // rejection shape; either way a superseded generation is not a real
      // failure — the barge-in path already reported it via onHaltPlayback.
      if (myGeneration !== this.generation) return
      this.options.handlers.onError(error instanceof Error ? error : new Error(String(error)))
    }
  }

  private bargeIn(): void {
    this.generation += 1
    this.currentAbort?.abort()
    this.options.handlers.onHaltPlayback()
    this.options.tts.interrupt(this.options.playbackClock.elapsedMs)
    this.setState('listening')
  }
}
